platform :ios, '9.0'

target 'CollectionViewDemo01' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SVProgressHUD', '2.2.5'
  pod 'SwiftyGif', '4.2.0'
  pod 'Kingfisher', '4.10.1'

end
