# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UserProfile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UserProfile
  pod 'SVProgressHUD', '2.2.5'
  pod 'SwiftyGif', '4.2.0'
  pod 'Kingfisher', '4.10.1'
  pod 'ObjectMapper'
  pod 'AFNetworking'

end
